# Generated by Django 5.0.3 on 2024-03-12 04:41

import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_authorization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('action_methods', models.ManyToManyField(blank=True, related_name='rest_user_action_method_set', related_query_name='rest_user_action_method', to='rest_authorization.actionmethod')),
                ('users', models.ManyToManyField(blank=True, related_name='rest_user_set', related_query_name='rest_user', to=settings.AUTH_USER_MODEL, verbose_name='Rest Framework Group Users')),
            ],
            options={
                'verbose_name': 'Rest Group',
                'verbose_name_plural': 'Rest Groups',
                'db_table': 'rest_group',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
